### ISSUE TITLE
 Aplication not found in Play Store, verify your app id. 

### ISSUE THREAD

**Issue by AbirAhsan** [kauemurakami/app_version_update#10]
It shows me, application not found in play store, when I use this ("com.abirahsan.drawingmaster") id . But it exists.
But I when I used another app's like facebook, ig's package name, then it's worked.
Then what's the problem ?

Here is my function, which I use under init method that's why when screen build then it can check.

```
 await AppVersionUpdate.checkForUpdates(
            appleId: appleId, playStoreId: playStoreId, country: country)
        .then((data) async {
      print(data.storeUrl);
      print(data.storeVersion);
      if (data.canUpdate!) {
        //showDialog(... your custom widgets view)
        //or use our widgets
        // AppVersionUpdate.showAlertUpdate
        // AppVersionUpdate.showBottomSheetUpdate
        // AppVersionUpdate.showPageUpdate
        AppVersionUpdate.showAlertUpdate(
            appVersionResult: data, context: context);
      }
    });
```

My error
```
Performing hot restart...                                               
Restarted application in 2,019ms.
E/flutter (  525): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception:  Aplication not found in Play Store, verify your app id. 
E/flutter (  525): #0      fetchAndroid (package:app_version_update/core/functions/fetch_version.dart:51:7)
E/flutter (  525): <asynchronous suspension>
E/flutter (  525): #1      fetchVersion (package:app_version_update/core/functions/fetch_version.dart:20:12)
E/flutter (  525): <asynchronous suspension>
E/flutter (  525): #2      AppVersionUpdate.checkForUpdates (package:app_version_update/app_version_update.dart:33:29)
E/flutter (  525): <asynchronous suspension>
E/flutter (  525): #3      _MyHomeScreenState.checkForUpdate (package:drawingmaster/pages/home_screen.dart:38:5)
E/flutter (  525): <asynchronous suspension>
E/flutter (  525): 
```

**Comment by pom11** [comment]
what is your version number?

**Comment by AbirAhsan** [comment]
> what is your store version number?

current version number is 1.0.0

**Comment by pom11** [comment]
it seems it doesn't appear in play.google.com response. is an error on their end. pls bump the version to 1.0.1 to force an update and retry again. thx

**Comment by kauemurakami** [comment]
we have problem with package info plus, I'm trying to solve this morning.
