### ISSUE TITLE
Unhandled Exception: ClientException: Connection closed before full header was received

### ISSUE THREAD

**Issue by VasilisPH** [kauemurakami/app_version_update#43]
I was debugging my app as always but now I got this error in the debug console. 

`E/flutter ( 7757): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ClientException: Connection closed before full header was received, uri=https://play.google.com/store/apps/details?id=com.APP_NAME.app`
`E/flutter ( 7757): #0      IOClient.send (package:http/src/io_client.dart:156:7)`
`E/flutter ( 7757): <asynchronous suspension>`
`E/flutter ( 7757): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)`
`E/flutter ( 7757): <asynchronous suspension>`
`E/flutter ( 7757): #2      _withClient (package:http/http.dart:167:12)`
`E/flutter ( 7757): <asynchronous suspension>`
`E/flutter ( 7757): #3      fetchAndroid (package:app_version_update/core/functions/fetch_version.dart:46:7)`
`E/flutter ( 7757): <asynchronous suspension>`
`E/flutter ( 7757): #4      fetchVersion (package:app_version_update/core/functions/fetch_version.dart:22:9)`
`E/flutter ( 7757): <asynchronous suspension>`
`E/flutter ( 7757): #5      AppVersionUpdate.checkForUpdates (package:app_version_update/app_version_update.dart:31:18)`
`E/flutter ( 7757): <asynchronous suspension>`
`E/flutter ( 7757): #6      versionChecking (package:live_like_local/resources/utilities/app_utils.dart:3581:33)`
`E/flutter ( 7757): <asynchronous suspension>`

P.S: "https://play.google.com/store/apps/details?id=com.APP_NAME.app" this link is valid and when i click it navigates me to the play store as expected.

**Comment by santhosh-D-subramani** [comment]
same here

**Comment by kauemurakami** [comment]
@VasilisPH @santhosh-D-subramani test a new releases, sorry for long time. I'm a little far from here
